# Generated by Django 4.0.4 on 2022-05-06 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubModel',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sub.base')),
                ('last', models.CharField(max_length=10)),
            ],
            bases=('sub.base',),
        ),
    ]
